TestProject/TestProject/Controllers/RolesController.cs
using Consts;
using Data;
using Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Services.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestProject.Mapping;
using TestProject.ViewModels.RoleVMs;

namespace TestProject.Controllers
{
    [Authorize(Roles = UserRoleConsts.ADMIN)]
    public class RolesController : Controller
    {
        private readonly RoleManager<Role> roleManager;
        private readonly FastScoreContext context;

        public RolesController(RoleManager<Role> roleManager, FastScoreContext context)
        {
            this.roleManager = roleManager;
            this.context = context;
        }

        public async Task<IActionResult> Get(string roleId)
        {
            var role = await context.Roles.FirstOrDefaultAsync(r => r.Id == roleId);

            if (role == null)
            {
                throw new ArgumentNullException();
            }

            ViewBag.roleId = roleId;

            var userRoleIds = context.UserRoles.Where(ur => ur.RoleId == roleId).Select(ur => ur.UserId);
            var users = context.Users.Where(u => userRoleIds.Contains(u.Id)).ToList();

            var roleInfoVM = new RoleInfoViewModel()
            {
                RoleId = roleId,
                RoleName = role.Name,
                UsersInRole = users
            };

            return View(roleInfoVM);
        }

        public async Task<IActionResult> GetAll()
        {
            var roles = await this.context.Roles.ToListAsync();
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateRoleViewModel createRoleVM)
        {
            if (ModelState.IsValid)
            {
                var role = InputMapper.Map(createRoleVM);

                var result = await roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    await context.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(createRoleVM);
        }

        public async Task<IActionResult> Edit(string roleId)
        {
            var role = await context.Roles.FirstOrDefaultAsync(r => r.Id == roleId);

            if (role == null)
            {
                throw new ArgumentNullException();
            }

            ViewBag.roleId = roleId;

            var userRoleIds = context.UserRoles.Where(ur => ur.RoleId == roleId).Select(ur => ur.UserId);
            var users = context.Users.Where(u => userRoleIds.Contains(u.Id)).ToList();

            var roleInfoVM = new RoleInfoViewModel()
            {
                RoleId = roleId,
                RoleName = role.Name,
                UsersInRole = users
            };

            return View(roleInfoVM);
        }

        [HttpPost]
        public IActionResult Edit(RoleInfoViewModel roleInfoVM)
        {
            return View();
        }
    }
}

TestProject/TestProject/Views/Roles/Create.cshtml
@model CreateRoleViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post">
    <div class="form-group">
        <label asp-for="RoleName"></label>
        <input asp-for="RoleName" class="form-control" placeholder="Enter role name"/>
    </div>
    <button type="submit" class="btn btn-primary">Create Role</button>
</form>

TestProject/TestProject/Views/Roles/Edit.cshtml
@model RoleInfoViewModel
@{ 
    var roleId = ViewBag.roleId;
}

<div class="form-group">
    <label asp-for="RoleId"></label>
    <input asp-for="RoleId" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="RoleName"></label>
    <input asp-for="RoleName" class="form-control" />
</div>
<div class="card">
    <h1 class="card-title">Users in role</h1>
    @if (!Model.UsersInRole.Any())
    {
        <h3>No users in this role yet</h3>
    }
    else
    {
        <ul>
            @foreach (var user in Model.UsersInRole)
            {
                <li class="card-text">@user.UserName</li>
            }
        </ul>
    }
    <div class="card-footer">
        <a class="btn btn-primary" asp-action="UpdateUsersRole" asp-controller="Account" asp-route-roleId="@roleId">Add or remove users</a>
    </div>
</div>

TestProject/TestProject/Views/Roles/GetAll.cshtml
@model IEnumerable<Role>

<a class="btn btn-primary"  asp-action="Create" asp-controller="Roles">Create new role</a>
@foreach (var role in Model)
{
    <div>
        <a asp-route-roleId="@role.Id" asp-action="Edit" asp-controller="Roles">@role.Name</a>
    </div>
}