TestProject/TestProject/Controllers/MatchesController.cs
using Data;
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestProject.Mapping;

namespace TestProject.Controllers
{
    public class MatchesController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly FastScoreContext context;

        public MatchesController(IUnitOfWork unitOfWork, FastScoreContext context)
        {
            this.unitOfWork = unitOfWork;
            this.context = context;
        }

        public async Task<IActionResult> GetByDate(int sportId, DateTime date)
        {
            var matchesByDate = await unitOfWork.MatchesService.GetByDate(sportId, date);

            if (!matchesByDate.Any())
            {
                var sport = await this.unitOfWork.MatchesService.GetByIdAsync(sportId);

                return PartialView("_NoMatchFound", sport.PhotoUrl);
            }

            var matchesByDateVM = ViewModelMapper.Map(matchesByDate);

            return PartialView("_GetMatches", matchesByDateVM);
        }

        public async Task<IActionResult> GetByMatchStatusId(int sportId, int matchStatusId, DateTime date)
        {
            var matchesByMatchStatusId = await unitOfWork.MatchesService.GetByMatchStatusId(sportId, matchStatusId, date);

            if (!matchesByMatchStatusId.Any())
            {
                var sport = await this.unitOfWork.MatchesService.GetByIdAsync(sportId);

                return PartialView("_NoMatchFound", sport.PhotoUrl);
            }

            return View("GetByDate", model: matchesByMatchStatusId);
        }
    }
}

TestProject/TestProject/Views/Shared/_GetMatches.cshtml
@model IDictionary<LeagueViewModel, IEnumerable<MatchViewModel>>
@inject IUnitOfWork unitOfWork;
@inject SignInManager<User> signInManager;
@using Consts;

@section Styles {
    <link href="~/css/matches.css" rel="stylesheet" />
    <link href="~/css/leagues.css" rel="stylesheet" />
}

@{
    User user = null;

    if (signInManager.IsSignedIn(User))
    {
        user = await unitOfWork.AccountService.GetByIdAsync(User.FindFirst(ClaimTypes.NameIdentifier).Value);
    }

    var sportId = Model.First().Key.LeagueSportId;
}

<div class="outer-match-added-div">
    <div class="inner-match-added-div">
        <div id="content">
        </div>
    </div>
</div>
<div class="column-special-container-manage-league">
    <div id="select-options" class="flex-row-manage-league">
        <span id="league-options-text">Select from the options:</span><img id="img-cross-close-manage-league" src="~/imges/darker_cross.png" />
    </div>
    <div id="manage-league" class="flex-row-manage-league">
        <img class="manage-league-star-img" src="~/imges/full_star.png"><span class="manage-league-text">Remove this league from My Leagues!</span>
    </div>
    <div id="manage-league-matches" class="flex-row-manage-league">
        <img /><span class="manage-league-matches-text">Add all games to favorite</span>
    </div>
</div>
<div class="outerContainer">
    <div class="innerContainer">
        <div class="content">
            Click for match details
        </div>
    </div>
</div>

@foreach (var kvp in Model)
{
    <div class="special-container-league">
        <div id="@kvp.Key.LeagueId" class="league-star-div">
            @if (user != null && user.Leagues.FirstOrDefault(l => l.Id == kvp.Key.LeagueId) != null)
            {
                <img id="@kvp.Key.LeagueId" class="league-star-img" src="~/imges/full_star.png" alt="starForFavoriteMatches" />
            }
            else
            {
                <img id="@kvp.Key.LeagueId" class="league-star-img" src="~/imges/empty_star.png" alt="starForFavoriteMatches" />
            }
        </div>
        <div>
            <img class="country-flag" src="@kvp.Key.LeagueCountryFlagPhotoUrl" alt="countryFlag" />
        </div>
        <div class="country-name-div">
            <span class="country-name">@kvp.Key.LeagueCountryName.ToUpper():</span>
        </div>
        <div class="league-name-div">
            <a class="league-name" asp-controller="Leagues" asp-action="GetById" asp-route-leagueId="@kvp.Key.LeagueId"><span>@kvp.Key.LeagueName</span></a>
        </div>
    </div>

    @foreach (var match in kvp.Value)
    {
        <div class="special-container-match">
            <div id="@match.MatchId" class="match-star">
                @if (user != null && user.FavoriteMatches.FirstOrDefault(m => m.Id == match.MatchId) != null)
                {
                    <img id="@kvp.Key.LeagueId" class="match-star-img" src="~/imges/full_star.png" />
                }
                else
                {
                    <img id="@kvp.Key.LeagueId" class="match-star-img" src="~/imges/empty_star.png" />
                }
            </div>
            <div id="@match.MatchId" class="match-div">
                <div class="special-container-match">
                    @switch (match.MatchStatusId)
                    {
                        case MatchStatusIdsConsts.SHEDULED:
                            <div class="match-info" id="match-starting-time">@match.StartingTime</div>
                            break;
                        case MatchStatusIdsConsts.FINISHED:
                            <div class="match-info">Finished</div>
                            break;
                        case MatchStatusIdsConsts.IN_PLAY:
                            if (match.FirstHalfCurrMinute != null)
                            {
                                <div class="match-info">
                                    <span class="match-info-curr-minute">
                                        <span class="curr-minute" matchId="@match.MatchId">@match.FirstHalfCurrMinute</span><span class="tick-sign">'</span>
                                    </span>
                                </div>
                            }
                            else
                            {
                                <div class="match-info">
                                    <span class="match-info-curr-minute">
                                        <span class="curr-minute" matchId="@match.MatchId">@(45+match.SecondHalfCurrMinute)</span><span class="tick-sign">'</span>
                                    </span>
                                </div>
                            }
                            break;
                        default:
                            throw new ArgumentException();
                    }
                    <div>
                        <div>
                            <img class="team-flag" src="@match.HomeTeamFlagPhotoUrl" /><span class="home-team-name" matchId="@match.MatchId">@match.HomeTeamName</span>
                        </div>
                        <div>
                            <img class="team-flag" src="@match.AwayTeamFlagPhotoUrl" /><span class="away-team-name" matchId="@match.MatchId">@match.AwayTeamName</span>
                        </div>
                    </div>
                    @if (match.MatchStatusId == MatchStatusIdsConsts.SHEDULED)
                    {
                        @if (!match.HasPreview)
                        {
                            <div class="dashes">
                                <div>
                                    -
                                </div>
                                <div>
                                    -
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="rectangle-preview"><a><span id="preview">PREVIEW</span></a></div>
                        }
                    }
                    else if (match.MatchStatusId == MatchStatusIdsConsts.FINISHED)
                    {
                        <div class="match-result">
                            <div class="match-final-result">
                                <div>
                                    @(match.FirstHalfHomeGoalsCount + match.SecondHalfHomeGoalsCount)
                                </div>
                                <div>
                                    @(match.FirstHalfAwayGoalsCount + match.SecondHalfAwayGoalsCount)
                                </div>
                            </div>
                            <div class="match-first-half-result">
                                <div>
                                    (@(match.FirstHalfHomeGoalsCount))
                                </div>
                                <div>
                                    (@(match.FirstHalfAwayGoalsCount))
                                </div>
                            </div>
                        </div>
                    }
                    else
                    {
                        if (match.FirstHalfCurrMinute == null)
                        {
                            <div class="match-result">
                                <div class="match-current-result" matchId="@match.MatchId">
                                    <div>
                                        @(match.FirstHalfHomeGoalsCount + match.SecondHalfHomeGoalsCount)
                                    </div>
                                    <div>
                                        @(match.SecondHalfHomeGoalsCount + match.SecondHalfAwayGoalsCount)
                                    </div>
                                </div>
                                <div class="match-first-half-result">
                                    <div>
                                        (@(match.FirstHalfHomeGoalsCount))
                                    </div>
                                    <div>
                                        (@(match.FirstHalfAwayGoalsCount))
                                    </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="match-result">
                                <div class="match-current-result" matchId="@match.MatchId">
                                    <div>
                                        @(match.FirstHalfHomeGoalsCount)
                                    </div>
                                    <div>
                                        @(match.FirstHalfAwayGoalsCount)
                                    </div>
                                </div>
                                <div class="match-first-half-result">
                                    <div>
                                        (@(match.FirstHalfHomeGoalsCount))
                                    </div>
                                    <div>
                                        (@(match.FirstHalfAwayGoalsCount))
                                    </div>
                                </div>
                            </div>
                        }
                    }

                    @if (match.MatchStatusId == MatchStatusIdsConsts.IN_PLAY)
                    {
                        <div matchStatusId="@match.MatchStatusId" class="live-bet"><span id="live">LIVE</span></div>
                        <div matchStatusId="@match.MatchStatusId" class="live-bet" style="display:none"><span id="bet">BET</span></div>
                    }
                    else if (match.MatchStatusId == MatchStatusIdsConsts.SHEDULED)
                    {
                        <div class="live-bet"><span id="live">LIVE</span></div>
                    }
                </div>
            </div>
        </div>
    }
}

@section Scripts {
    <script src="/js/matches.js"></script>
}

TestProject/TestProject/Views/Shared/_Layout_Tennis.cshtml
@inject SignInManager<User> signInManager;
@inject UserManager<User> userManager;
@inject IUnitOfWork unitOfWork;
@inject FastScoreContext context;

@{
    User user = null;

    @if (User.Identity.IsAuthenticated)
    {
        var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
        user = await context.Users.Include(u => u.FavoriteMatches).FirstOrDefaultAsync(u => u.Id == userId);
        var userFavorites = user.FavoriteMatches;
    }

    var sports = await unitOfWork.SportsService.GetAll();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site_tennis.css" />
    <link href="~/css/secondNavBar.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light">
            <div class="container">
                <a class="navbar-brand" style="color:white" asp-area="" asp-controller="Home" asp-action="Index">
                    <div class="special-container">
                        <div class="image">
                            <img id="logo" src="~/imges/Uvf86ufG_400x400.png" />
                        </div>
                        <div class="text">
                            <p><span class="logoText">FastScore</span><span class="logoText" style="font-size: 12px;">We deliver scores faster</span></p>
                        </div>
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar -collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Logout @user.UserName</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" id="login" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="register" asp-area="" asp-controller="Home" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
        <nav id="bottomNav" class="navbar navbar-expand-sm navbar-light">
            <div class="container">
                <div class="navbar -collapse collapse d-sm-inline-flex flex-sm-row-reverse" style="background-color:darkgreen">
                    <ul class="navbar-nav flex-grow-1 ml-auto">
                        @foreach (var sport in sports)
                        {
                            @if (sport.IsFavoriteSport)
                            {
                                <li class="nav-item">
                                    <a asp-action="GetTodayMatches" asp-controller="Matches" asp-route-sportId="@sport.Id" class="sports">
                                        <div class="special-container">
                                            <div class="image">
                                                <img class="sportsImg" src="@sport.PhotoUrl" />
                                            </div>
                                            <div class="text">
                                                @sport.Name
                                            </div>
                                            <div class="dot">1</div>
                                        </div>
                                    </a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TestProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TestProject/TestProject/Views/Shared/_NoMatchFound.cshtml
@model string


<div id="container">
    <img style="margin-left:auto; margin-right:auto; width:20px; height:20px; display:block" src="@Model" />
    <p style="margin-left:auto; margin-right:auto; text-align:center">No match found.</p>
</div>